name: Setup

description: Setup

inputs:
  google_services:
    description: 'Google Services file'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 17
    - uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

    - name: Check Gradle wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Put Google Services file
      env:
        GOOGLE_SERVICES: ${{ inputs.google_services }}
      run: echo "$GOOGLE_SERVICES" | base64 -d > app/google-services.json
      shell: bash
