version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: cimg/android:2021.10.2-node
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Assemble
          command: ./gradlew assemble

  tests:
    working_directory: ~/code
    docker:
      - image: cimg/android:2021.10.2-node
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Unit Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: core/build/reports
          destination: core/reports
      - store_artifacts:
          path: solana/build/reports
          destination: solana/reports
      - store_test_results:
          path: core/build/test-results
      - store_test_results:
          path: solana/build/test-results

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - tests:
          requires:
            - build
